language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - pip install pytest
install:
  - pip install -e .
script:
  - pytest
